apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-java-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-java-app
  template:
    metadata:
      labels:
        app: simple-java-app
    spec:
      containers:
      - name: app
        image: mlearn774/simple-java-app:latest
        imagePullPolicy: Always  
        ports:
        - containerPort: 8080

